application: hello
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: hello.application


#default_expiration: "4d 5h"

#derived_file_type:
#- python_precompiled

# sontek didn't need to specify setuptools, but Reed & Chris did, on
# two different platforms

libraries:
- name: webob
  version: "1.2.3"
- name: setuptools
  version: 0.6c11


# - name: pycrypto
#   version: latest
# - name: markupsafe
#   version: latest

# skip_files:
# - ^(.*/)?app\.yaml
# - ^(.*/)?app\.yml
# - ^(.*/)?index\.yaml
# - ^(.*/)?index\.yml
# - ^(.*/)?#.*#
# - ^(.*/)?.*~
# - ^(.*/)?.*\.py[co]
# - ^(.*/)?.*/RCS/.*
# - ^(.*/)?\..*
# - ^(.*/)?.*/tests.*
# - ^distlib/pyramid/scaffolds.*
# - ^(.*/)?.*/.svn/.*
# - ^(.*/)?.*/.git/.*
# - ^(.*/)?.*/.gitignore
# - ^Crypto/*
# - ^(.*/)?.*\.less
# - ^(.*/)?.*\.mustache
# - ^(.*/)?.*\.md
# - ^(.*/)?.*\.rst
# - ^.*LICENSE.*

# error_handlers:
#   - file: default_error.html

# handlers:

# - url: /favicon.ico
#   static_files: static/favicon.ico
#   upload: static/favicon.ico
#   expiration: "30d"

# - url: /static
#   static_dir: static
#   expiration: "30d"

# - url: .*
#   script: main.application
